version: '2.1'

services:
  patchpanda:
    image: patchpanda-app
    container_name: patchpanda
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5091:8080"
    restart: unless-stopped
    networks:
      - internal
    environment:
      - APPS_HOST_PATH=/home/trixx/Applications
    volumes:
      - /home/trixx/Applications:/media/apps:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw

networks:
  internal:
    external: true