version: '2.1'

services:
  patchpanda:
    image: patchpanda-app
    container_name: patchpanda
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5091:8080"
    restart: unless-stopped
    networks:
      - internal
    env_file:
      - .env
    volumes:
      - /home/trixx/Applications:/home/trixx/Applications:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw

networks:
  internal:
    external: true